name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install server dependencies
        run: yarn install
      - name: Server side unit tests
        run: yarn test
      - name: Start server
        run: yarn run start &
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          working-directory: client
          build: yarn run build
          start: yarn run start
          wait-on: http://localhost:3000
      - name: Archive screenshots
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          working-directory: client
          name: cypress-screenshots
          path: cypress/screenshots
