name: End-to-end tests
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install server dependencies
        run: yarn install
      - name: Server side unit tests
        run: yarn run e2e
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
      - name: Client side unit tests
        run: yarn run test
        with:
          working-directory: client
      - name: Start server for e2e tests
        run: yarn run start &
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          working-directory: client
          build: yarn run build
          start: yarn run start
          wait-on: http://localhost:3000
      - name: Archive screenshots
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: client/cypress/screenshots
